name: Linter

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Lint Swift code with SwiftFormat
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache SPM build
        uses: actions/cache@v2
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Run SwiftFormat
        run: |
          swift run -c release swiftformat --lint .

      - name: Report error
        if: ${{ failure() }}
        run: |
          echo '::error::SwiftFormat linting failed. Run `Scripts/swiftformat` to format your code.'
